# Generated by Django 4.2 on 2023-06-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ask_C', '0002_patient_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patient_list',
            new_name='add_patient',
        ),
    ]
