# Generated by Django 4.2 on 2023-06-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ask_C', '0003_rename_patient_list_add_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_patient',
            new_name='Addpatient',
        ),
    ]
